### ISSUE TITLE
About attaching the interceptor during page load

### ISSUE THREAD

**Issue by sul4bh** [bassettsj/protractor-intercept#2]
I am trying to log all HTTP requests that are made during a page load. I cannot reliably do it because I cannot attach the interceptor during page loa.

What would be a good strategy to attach this interceptor reliably during page load?

**Comment by bassettsj** [comment]
@sul4bh I don't think this module would be helpful for you. I think using something specific for the browser you're targeting would be good, maybe something like the logging explained in this article would be good: http://eitanp461.blogspot.com/2014/01/advanced-protractor-features.html

**Comment by sul4bh** [comment]
Thanks for the quick reply and that link

The alternative that I am working on is using console.log() to share the url with protractor.
